### PR TITLE
adding links

### LINKED ISSUE #2: Hyperlink to subreddits

### PR DESCRIPTION
**Pull request by danhogan**
Closes #2

### CODE REVIEW

**Comment by PatMyron** [comment]
@danhogan thanks Dan, would love to know how you found the page / what you've been using it for!

**Comment by danhogan** [comment]
Good move using old reddit.

I was trying to gauge how popular different EPL teams are (thanks Ted Lasso) so I googled something like "epl teams by reddit subscribers" and landed on [this post](https://www.reddit.com/r/PremierLeague/comments/ap7ixx/epl_team_subreddits_by_number_of_subscribers/), which then led me to your site.

My first thought was "some logos would be nice here" 😄
My second thought was about making things clickable. I had Hacktoberfest on the mind and I clicked your issues tab to find you had already thought about it too. I like charts and I knew that was something I could add pretty quickly, so I just went for it.

**Comment by PatMyron** [comment]
> I like charts and I knew that was something I could add pretty quickly

[Upgrading `chart.js` to v3](https://www.chartjs.org/docs/latest/migration/v3-migration.html) and stuck on `TypeError: Cannot read properties of undefined (reading 'label')`

<details>

<summary>after these edits:</summary>

```diff
-    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" integrity="sha256-Uv9BNBucvCPipKQ2NS9wYpJmi8DTOEfTA/nH2aoJALw=" crossorigin="anonymous"></script>
+    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.9.1/chart.min.js" integrity="sha512-ElRFoEQdI5Ht6kZvyzXhYG9NqjtkmlkfYk0wr6wHxU9JEHakS7UJZNeml5ALk+8IKlU6jDgMabC3vkumRokgJA==" crossorigin="anonymous"></script>


-                            xAxes: [{
-                                gridLines: {
+                            x: {
+                                grid: {
                                     display: false
                                 },
                                 ticks: {
                                     autoSkip: false,
                                 }
-                            }],
-                            yAxes: [{
+                            },
+                            y: {
                                 ticks: {
                                     beginAtZero: true
                                 }
-                            }]
+                            }
```

</details>

@danhogan know how to port label-reading to v3?

**Comment by danhogan** [comment]
@PatMyron 
I think along with your changes, we need to redo that `barClick` function. It looks like this works:
```js
function barClick(event, elements){
    const index = elements[0].index;
    const chart = elements[0].element.$context.chart;
    window.open(`https://old.reddit.com/r/${chart.data.labels[index]}`, '_blank').focus();
}
```

**Comment by PatMyron** [comment]
Works! Quite nested inheritance to get `labels` in v3. Many properties, and I was stuck sifting through since it was a circular structure:
https://stackoverflow.com/q/11616630/print-circular-structure-in-a-json-like-format
https://stackoverflow.com/q/4816099/chrome-sendrequest-error-typeerror-converting-circular-structure-to-json
https://stackoverflow.com/q/10392293/stringify-convert-to-json-a-javascript-object-with-circular-reference/

**Pull request merged**
